__include__: [
  '../dfine/dfine_hgnetv2_s_custom.yml',
  '../dataset/URPC_detection.yml',
  '../base/deim.yml'
]

print_freq: 400
output_dir: ./outputs/UTDAC-deim-S

model: DEIM_MG

DEIM_MG:
  yaml_path: configs/cfg-improve/dfine-s-test.yaml

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*(bn|norm)).*$'
      lr: 0.0002
    - 
      params: '^(?=.*(?:norm|bn)).*$'     # except bias
      weight_decay: 0.

  lr: 0.0004
  betas: [0.9, 0.999]
  weight_decay: 0.0001


# Increase to search for the optimal ema
epoches: 300 # 148 + 12

## Our LR-Scheduler
flat_epoch: 148   # 4 + epoch // 2, e.g., 40 = 4 + 72 / 2
no_aug_epoch: 12

## Our DataAug
train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [4, 148, 288]   # list

  collate_fn:
    mixup_epochs: [4, 148]
    stop_epoch: 288
    base_size_repeat: ~
  total_batch_size: 8
val_dataloader:
  total_batch_size: 8