print_freq: 400
output_dir: './logs'
checkpoint_freq: 100
plot_train_batch_freq: 100

sync_bn: True
find_unused_parameters: True
verbose_type: 'origin' # origin:原始的输出方式 progress:进度条形式

use_amp: False
scaler:
  type: GradScaler
  enabled: True


use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000

cache_imgsz: 960
ram_cache: False

yolo_metrice: True # 需要输出YOLO指标的设置为True