__include__: [
  './rtdetrv2_r18vd_120e_coco.yml',
  '../base/rt_deim.yml',
]

output_dir: ./outputs/deim_rtdetrv2_r18vd_120e_coco

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.0001

# change part
epoches: 300
flat_epoch: 154    # 4 + 120 / 2
no_aug_epoch: 3

train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [4, 154, 297]   # list 
      
  collate_fn:
    mixup_epochs: [4, 154]
    stop_epoch: 297